# application.properties íì¼ì í­ì resourceí´ë ë°ë¡ ìë ë§ë ë¤.
# ëª©ì  : ì¤íë§ ìë²ê° ì¤íë  ë ì¤ì ì ë¡ë©íë íì¼
# ì£¼ìí ëë # ì¬ì©íë¤.
# ì°¸ê³  : ìë¨ë©ë´ -> ì¤ì  -> 'ì¸ì½ë©'ê²ì -> íì¼ ì¸ì½ë© ë©ë´ í´ë¦­
#  íë¡í¼í° íì¼ì ëí ëí´í¸ ì¸ì½ë© : UTF-8 ë³ê²½

# 1. ë´ì¥ AWS PORT(íë¡ê·¸ë¨ìë³ë²í¸) ë²í¸ ë³ê²½ , ê¸°ë³¸ê°ì 8080 ì´ë©° ìì  ê°ë¥.
server.port = 8080

# 2. DAO ê° ìë íë¡í¼í° íì¼ìì DBì°ë ê°ë¥íë¤. JDBC
# 2-1 ì°ëí  dbìë²ì ì£¼ì
#spring.datasource.url=jdbc:mysql://localhost:3306/mydb0303
#spring.datasource.url=jdbc:mysql://localhost:3306/mydb0304
#spring.datasource.url=jdbc:mysql://localhost:3306/practice5
#spring.datasource.url=jdbc:mysql://localhost:3306/mydb0305
#spring.datasource.url=jdbc:mysql://localhost:3306/boardservice10
#spring.datasource.url=jdbc:mysql://localhost:3306/mydb0309
#spring.datasource.url=jdbc:mysql://localhost:3306/practice7
#spring.datasource.url=jdbc:mysql://localhost:3306/mydb0311
#spring.datasource.url=jdbc:mysql://localhost:3306/mydb0313
#spring.datasource.url=jdbc:mysql://localhost:3306/mydb0317
#spring.datasource.url=jdbc:mysql://localhost:3306/teskdb
spring.datasource.url=jdbc:mysql://localhost:3306/springweb


# 2-2 ì°ëí  dbìë²ì ê³ì /ë¹ë°ë²í¸ , ëì´ì°ê¸° ì£¼ì
spring.datasource.username=root
spring.datasource.password=1234

# 2-3 Entity íì´ë¸ ìì±/ìì   , DDL : sqlì ìì´ *ê°ë°ë¨ê³* ëë²ê¹(íì¸ì©) *ì´ì/ë°°í¬ ë¨ê³ ì¬ì©íì§ ìëë¤*
# create : ìë²ì¤íí ëë§ë¤ ì­ì í ìì±
# update : ìë²ì¤íí ëë§ë¤ ì¡´ì¬íë©´ ìì  ì¡´ì¬íì§ ìì¼ë©´ ìì±
# none : ì¬ì©ìí¨.
spring.jpa.hibernate.ddl-auto = create

# 2-4 ì½ìì°½ì ìëì¼ë¡ ì¤íë sql íì *ê°ë°ë¨ê³* ëë²ê¹(íì¸ì©) *ì´ì/ë°°í¬ ë¨ê³ ì¬ì©íì§ ìëë¤*
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# SQL ë´ ë§¤ê°ë³ì ê°ë¤ì íì * ì´ì/ë°°í¬ ì ëª¨ëí°ë§(ì ì§ë³´ì) ì¬ì© ëë ê²½ì°
logging.level.org.hibernate.orm.jdbc.bind = TRACE
logging.level.org.hibernate.sql = DEBUG

# 2-5 ìë² ì¤í í ë SQL íì¼ ì¤í *ê°ë°ë¨ê³* , always,none *ì´ì/ë°°í¬ ë¨ê³ ì¬ì©íì§ ìëë¤*
#spring.sql.init.mode=always
# 2-6 ìë² ì¤í í ë classpath(resourcesí´ë) ì´í ì data.sql íì¼ ê²½ë¡ ì§ì 
spring.sql.init.data-locations=classpath:/sql/data.sql
# 2-7 ìë² ì¤í í ë JPAê° ì´ê¸°í íì¼ ì¤í
spring.jpa.defer-datasource-initialization = true